version: '3.7'
services:
  kafka:
    image: spotify/kafka
    restart: always
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
    # ports:
    #   - '9092:9092'
    #   - '2181:2181'

  elasticsearch:
    image: elasticsearch:7.7.0
    restart: always
    environment:
      discovery.type: single-node
    # ports:
    #   - '9200:9200'

  twitter-crawler:
    build:
      context: .
      dockerfile: twitter-crawler/Dockerfile
    restart: always
    environment:
      KAFKA_HOST: 'kafka:9092'
      KAFKA_PUBLISH_TOPIC: 'resources'
    env_file: .env
    # .env file should contain:
    #   TWITTER_CONSUMER_KEY
    #   TWITTER_CONSUMER_SECRET
    #   TOKEN
    #   TWITTER_TOKEN_SECRET
    depends_on: [kafka]

  mentions-matcher:
    build:
      context: .
      dockerfile: mentions-matcher/Dockerfile
    restart: always
    environment:
      KAFKA_HOST: 'kafka:9092'
      KAFKA_SUBSCRIBE_TOPIC: 'resources'
      KAFKA_PUBLISH_TOPIC: 'mentions'
    depends_on: [kafka]

  mentions-storage:
    build:
      context: .
      dockerfile: mentions-storage/Dockerfile
    restart: always
    environment:
      ELASTICSEARCH_HOST: 'elasticsearch:9200'
      KAFKA_HOST: 'kafka:9092'
      KAFKA_SUBSCRIBE_TOPIC: 'mentions'
    depends_on: [kafka, elasticsearch]

